name: 'Release'

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Restore packages
        run: dotnet restore
      - name: Build packages for release
        run: dotnet pack --no-restore -c Release -p:PackageVersion=$(echo $GITHUB_REF | cut -d / -f 3  | cut -c2-)
      - name: Publish packages
        run: |
          dotnet nuget push src/*/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source "https://api.nuget.org/v3/index.json"
